builds:
  -
    env:
      - GO111MODULE=on
    binary: google-suggest
    main: ./cmd/google-suggest/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
    ldflags:
      - -s -w -X 'main.Name=google-suggest' -X 'main.Version={{.Version}}'
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
release:
  github:
    owner: saihon
    name: google-suggest
  draft: true